name: Clang tests
on: [ push,pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -laR
      - run: mkdir _build
      - run: export CC=clang
      - run: cd _build && cmake ../dragoneer
      - run: ls -lRa

