name: MSVC on Windows
on: [ push, pull_request ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: tree
      - run: mkdir _build
      - run: cd _build && cmake ../dragoneer -- target example-list-usage example-animal-oop
      - run: tree
      - run: cmake --build _build
      - run: tree